#! /usr/bin/env python

from __future__ import absolute_import, print_function
import sys

if len(sys.argv) < 2:
	print("find_user: missing user id")
	exit()
else:
	user = sys.argv[1]

import tweepy
import pprint 
import time

import yaml
import os
stream = open( os.path.expanduser('~') + "/.twittercl.yaml", "r")
keys = yaml.load(stream)
consumer_key=keys['consumer_key']
consumer_secret=keys['consumer_secret']
access_token=keys['access_token']
access_token_secret=keys['access_token_secret']


pp = pprint.PrettyPrinter(indent=4)

def warning(*objs):
    print("WARNING: ", *objs, file=sys.stderr)


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.secure = True
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

# If the authentication was successful, you should
# see the name of the account print out
result = 0
while result == 0:
	try:
		result = api.get_user(user)
	except tweepy.RateLimitError:
		warning("Rate limit exhausted. sleeping...")
		time.sleep(5*60)

if len(sys.argv) < 3:
	pp.pprint(result._json)
else:
	for i in range(2,len(sys.argv)):
		print( str(result._json[sys.argv[i]]) + "\t", end="")
	print()


