#! /usr/bin/env python

from __future__ import absolute_import, print_function
import sys

if len(sys.argv) < 2:
	print("find_user: missing user id")
	exit()
else:
	user = sys.argv[1]

import tweepy
import pprint 

import yaml
import os
stream = open( os.path.expanduser('~') + "/.twittercl.yaml", "r")
keys = yaml.load(stream)
consumer_key=keys['consumer_key']
consumer_secret=keys['consumer_secret']
access_token=keys['access_token']
access_token_secret=keys['access_token_secret']


pp = pprint.PrettyPrinter(indent=4)



auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.secure = True
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

# If the authentication was successful, you should
# see the name of the account print out
if len(sys.argv) < 3:
	pp.pprint(api.get_user(user)._json)
else:
	pp.pprint(api.get_user(user)._json[sys.argv[2]])


