#! /usr/bin/env python

from __future__ import absolute_import, print_function
import sys

if len(sys.argv) < 2:
	print("find_user: missing user id")
	exit()
else:
	user = sys.argv[1]

import warnings
import tweepy
import time

import yaml
import os
stream = open( os.path.expanduser('~') + "/.twittercl.yaml", "r")
keys = yaml.load(stream)
consumer_key=keys['consumer_key']
consumer_secret=keys['consumer_secret']
access_token=keys['access_token']
access_token_secret=keys['access_token_secret']


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.secure = True
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
user = api.get_user(user).id

def get_followers(username):
	i=-1
	followers = []
	while i==-1 or len(followers):
		followers = []
		while len(followers) == 0:
			try:
				followers = api.followers_ids(user,page=i)
			except:
				warnings.warn("Rate limit exceeded. sleeping...")
				time.sleep(15*60)
		if len(followers)>0:
			for f in followers:
				yield f
		i+=1

for u in get_followers(user):
	print(str(user) + "\t" + str(u))



