#! /usr/bin/env python

from __future__ import absolute_import, print_function
import sys

if len(sys.argv) < 2:
	print("find_user: missing user id")
	exit()
else:
	user = sys.argv[1]

import tweepy
import time

import yaml
import os
stream = open( os.path.expanduser('~') + "/.twittercl.yaml", "r")
keys = yaml.load(stream)
consumer_key=keys['consumer_key']
consumer_secret=keys['consumer_secret']
access_token=keys['access_token']
access_token_secret=keys['access_token_secret']


auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.secure = True
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
user = api.get_user(user).id

def warning(*objs):
    print("WARNING: ", *objs, file=sys.stderr)

def get_friends(username):
	c=-1
	friends = []
	while c!=0 :
		friends = []
		while len(friends) == 0:
			try:
				friends = api.friends_ids(username,cursor=c)
			except tweepy.RateLimitError as e:
				warning("Rate limite exhausted. sleeping..")
				time.sleep(5*60)
		if len(friends)>0:
			for f in friends[0]:
				yield f
		c=friends[1][1]
		warning("about to check for more friends")
		time.sleep(2)

for u in get_friends(user):
	print(str(user) + "\t" + str(u))



